project:
  type: website
  output-dir: docs

website:
  title: "Instructor Blog for *Lessons in Statistical Thinking*"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: cosmo
    css: styles.css



