---
title: "Risk and Evidence in the Space Age"
author: "Daniel Kaplan"
date: "2024-06-25"
categories: [bayes, subjective probability, NASA]
---

In the 1970s and 1980, following up on the successful moon-landing Apollo program of the 1960s, NASA embarked on a program to develop a space launch system called the "Space Shuttle" that would dramatically lower the cost per kilogram of placing objects into low-earth orbit. After many delays and massive cost overruns, the first Space Shuttle, Columbia, was launched on a manned test flight in April 1981.

From 1985 through mid-January 1986, NASA's launch rate was 1 launch every 4 to 5 weeks, with some separated by as little as 3 weeks. This showed progress toward the promised one launch per week pace. NASA scheduled mission 25 to fly just two weeks after mission 24.

Launching the shuttle was a risky proposition. Adam Higginbotham's excellent 2024 book, *Challenger: A True Story of Heroism and Disaster on the Edge of Space* gives a detailed and up-close account of NASA decision making. Several of the launches were close calls, some of them coming within a few seconds of disaster. One of the closest of these, in January 1985, produced severe internal damage to a critical joint in a solid-rocket booster. This problem was associated with the record-breaking cold weather in the days before launch. Plans were made to re-design the joint, but since the cold weather was a "one in one-hundred year" event, this was not an urgent concern. 

Upper management at the contractor that designed and built the solid-rocket booster, Morton-Thiocol, did not draw attention to the damage found after the 1985 flight, but internally added a new requirement for launch decisions: the temperature must be above 54 degrees.

Mission 25 (officially STS-51-L) was launched on 28 January 1986. The weather in the days before and during launch was again record-breaking cold, at 28 degrees substantially colder than the previous January 1985 record. 

Before every flight, NASA conducted an intensive pre-flight safety review before giving the go for launch. Many scheduled launches had been cancelled as the result of such reviews. The Morton-Thiocol engineers, heeding the 54-degree criterion for launch, recommended a "no go" decision, but upper management overrode this, partly at the urging of NASA officials.  Unfortunately,  
 
The space shuttle Challenger exploded 73 seconds into its mission, killing all seven astronauts.

In the weeks after the explosion, NASA management, now aware of the cold-weather theory, instead insisted that the disaster was the result of an unknown but highly improbable technical failure. Was this a reasonable response based on the readily available data: the temperature at launch and the explosion itself?

Publicists for NASA had described the risk of catastrophic failure as "one in a million." This must be regarded as hyperbole; it's clearly absurd to base such a claim on the empirical basis of 24 successful launches. NASA managers knew that the risk was higher. Any assessment of the risk on such limited evidence must be subjective. If the risk had been reckoned as one-in-a-hundred, Mission 25 would never have been proposed in the first place. For our purposes, then, suppose that the NASA managers' intuition put the risk at 0.001 or lower. 

After the accident, should the managers have continued to believe in the 0.001 risk even after they knew about the cold-weather theory? We can approach this question using Bayesian inference.

Consider two, competing hypotheses. The first is "business as usual," that the risk for Mission 25 is no different than for other missions. The second hypothesis is "cold-weather risk."

For the business-as-usual hypothesis, the *likelihood* of a disaster is, as stipulated above, 0.001 or smaller. Under the cold-weather risk hypothesis, the engineers who designed the solid-rocket booster thought a disaster was quite likely. We'll translate this into a numerical likelihood of 0.1.

To complete the Bayesian calculation, we need to state the prior probability of the cold-weather-condition hypothethesis. However skeptical the NASA management might be about the cold-weather risk hypothesis, once they knew about the previous warnings from engineers and the internal Morton-Thiokol 54-degree launch criterion, a reasonable prior might be a probability of 0.10 (corresponding to odds of 0.11). 

Psychologically, the NASA managers would have had a hard time accepting the cold-weather-risk hypothesis. For people in their position, it's tempting to interpret a probability for that hypothesis of 0.10 as meaning "not likely." However, after the observation of the explosion, the prior probability needs to be updated.

The posterior odds of the cold-weather hypothesis can be calculated as the prior odds multiplied by the likelihood ratio. This gives:

$$\underbrace{\frac{0.1}{0.001}}_\text{likelihood ratio} \underbrace{0.11}_\text{prior odds} = \underbrace{11}_\text{posterior odds} .$$

The posterior odds for the cold-weather hypothesis practically exclude the business-as-usual hypothesis. 

Discussion points:

* Suppose the launch of Mission 25 had been successful. Would the posterior odds for the cold-weather-theory be much different than the prior odds?

* Does a risk of 0.001 imply safety? 

* Naturally, the three numbers involved in this analysis, 0.1, 0.001, and 0.11, are all subjective. Explore the sensitivity of the calculated posterior odds to changes in these numbers.




