---
title: "Instructor's Guide to Starting with WebR"
author: "Daniel Kaplan"
date: "2024-05-01"
categories: [LSTbook, computing, WebR]
# Enable webR
webr:
  channel-type: 'automatic'
  packages: ['ggplot2', 'dplyr', 'LSTbook', 'ggformula', 'mosaicData', 'moderndive', 'palmerpenguins', 'babynames', 'stringdist', 'mosaicData']
filters:
  - webr
---

These notes are intended for instructors who want to get started or experiment with using WebR in their notes/assignments/etc. for students.
WebR is a full-featured version of R that runs in the student's browser.

::: {.callout-note}
## Help refine this document

This document is useful only insofar as instructors can make sense of it. If you find it confusing, please let me know so that I can fix it. Write to me at `kaplan@macalester.edu`.
:::

Using WebR has advantages both for the student and the instructor. 

- Documents including computation are ordinary HTML (+  JavaScript) that can be posted on the web in straightforward ways.
- There is no need to set up a server.
- Computation can be positioned close to the text narrative that explains it or close to the exercise that a student is working on. 
- Any packages required can be easily specified by the instructor and will be automatically loaded into the document's WebR session.
- The interface is much simpler than RStudio. That said, the instructor herself will develop the documents using RStudio. And some instructors encourage students to write RMarkdown documents to record their work. That doesn't work at all in WebR. 

The word "chunk" is used for a block of executable code embedded in a document. @lst-base-graphics is an example of a WebR chunk with an R statement pre-positioned inside. The R code can be edited or entirely replaced by the student working with the chunk. Press "Run Code" to carry out the computation.

::: {#lst-base-graphics}
```{webr-r}
plot(mpg ~ wt, data = mtcars)
```
:::

The markup to create a chunk is very simple. For the above chunk it is

````markdown
```{webr-r}
plot(mpg ~ wt, data = mtcars)
```
````

::: {.callout-note}
## `{ggplot2}` and related graphics.

In @lst-base-graphics I have used base R graphics just for the convenience of the reader. You can also use `{ggplot2}` graphics, perhaps with the `{ggformula}` interface. To demonstrate this, here are some more webr chunks. You could equally well paste their contents into the previous chunk.

```{webr-r}
mtcars |> 
  ggplot(aes(x = wt, y = mpg)) + 
  geom_point(color = "blue")
```

`{ggformula}` graphics:
```{webr-r}
mtcars |> gf_point(mpg ~ wt, color = "brown")
```

Graphics from [*Lessons in Statistical Thinking*](https://dtkaplan.github.io/Lessons-in-statistical-thinking/L02-Pointplots.html#point-plot):
```{webr-r}
mtcars |> point_plot(mpg ~ wt, annot = "model")
```
:::

## Preliminaries

We will use the [*quarto*](https://quarto.org/) system for producing HTML documents. Consequently, a first step is to install *quarto* on your computer. You need version 1.4 (or later), so even if you have already been using *quarto*, you may need to update. [To find out, give this command in your **terminal**: `quarto --version`]{.aside} Follow the "Get Started" link on the [*quarto*](https://quarto.org/) homepage.

*Quarto* is a stand-alone program. You will be using it from RStudio, but there are a couple of occasions when you will use the **terminal* rather than the R console to set things up.

We presume that you have R and RStudio installed. If you are not familiar with RStudio, you will need to become so before you can make sense of the following instructions.

At this point, we won't worry about how to deploy the documents you write on a web site. You can write functioning documents without this. That way you can try out WebR before having to set up a web site. (See web documentation on "quarto blog site" (e.g. [this page](https://quarto.org/docs/publishing/)) if you're curious about how to set up a suitable web site.)

## Producing your first document

There's an excellent [four-minute video](https://youtu.be/DoRR2S5lLvk?t=5) by James Balamuta, the *Coatless Professor*. This covers just about everything you need to get started (once you have installed *quarto* and RStudio), including creating an RStudio project and a *quarto* document.

Take care to note what is clearly shown at time 1:38 in the video, the very brief use of the **terminal** (as opposed to the R console) to give the command up the RStudio project to use WebR. 

```rmarkdown
quarto add coatless/quarto-webr
```

You can create many documents within one project. You only have to do the `quarto add ...` once for each project. After that, you work only in RStudio.

The *Coatless Professor*'s video brings you all the way through displaying a working WebR document in the RStudio "Viewer" tab. But you can equally well open the document in a browser. (On the Viewer tab menu bar, click the "Show in New Window" button, which looks like a sheet of paper with an upward-facing arrow.)

The *Coatless Professor* provides more links to information [on this GitHub web page](https://github.com/coatless/quarto-webr?tab=readme-ov-file). Those not familiar with GitHub may be put off by the material at the top of the page. Simply scroll down until you get to the part that looks like an ordinary web page.

## Editing your document

The *Coatless Professor* video shows you the very few steps needed to set up your document for WebR. I want to elaborate just a little bit.

At the top of the example document there is a header, delimited by lines with `---`, that contains information used by the *quarto* system. This information is written in a format called "YAML." Keep that name in mind. 

```{verbatim}
#| code-copy: true
---
title: webR in Quarto HTML Documents
format: html
engine: knitr
filters:
  - webr
---
```

You're free to edit the title, but leave the other items alone. YAML is very sensitive to formatting errors.

The example document sets up a WebR session using base R. Many instructors will want to access R packages. To set up the document to do this automatically, add the following to the YAML header (inside the `---` delimiters). (Use the <i class="bi bi-clipboard) to copy the contents to the clipboard before pasting into your *quarto* document.)

``` {r eval=FALSE}
#| code-copy: true
webr:
  channel-type: 'automatic'
  packages: ['ggplot2', 'dplyr', 'LSTbook', 'ggformula', 'mosaicData', 'moderndive', 'palmerpenguins', 'babynames', 'stringdist', 'mosaicData']
```

The particular packages listed are those I use in the [*Lessons*](https://dtkaplan.github.io/Lessons-in-statistical-thinking) book. You may want to exclude some of these or include others (such as the `{mosaic}` package.) For those packages listed, you will not have to use the `library()` command in your WebR document. Neither do you need to `install.packages()`, this happens automatically. (Note that you can use `library()` in a WebR chunk, if that suits your pedagogy.)

## Moving forward ...

Once you have gained experience creating WebR *quarto* documents, you will want to learn how to deploy them to a web server so that your students can use them, too. That's a [multi-stage process to initialize](../WebR-on-github-pages), but much simpler in day-to-day use.
